version: 2
updates:
  - package-ecosystem: npm
    directory: "/ui"
    schedule:
      interval: "monthly"
  - package-ecosystem: npm
    directory: "/api-client"
    schedule:
      interval: "monthly"
