# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: check bash scripts
        args: ["-x", "--severity=error"]
  - repo: local
    hooks:
      - id: install
        name: install project
        language: system
        always_run: true
        pass_filenames: false
        entry: npm install
      - id: lint
        name: lint project
        language: system
        always_run: true
        pass_filenames: false
        entry: npm run lint -ws -- --write
      - id: build
        name: build project
        language: system
        always_run: true
        pass_filenames: false
        entry: npm run build -ws
