name: Main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 20

      - name: Installing Dependencies
        run: npm install

      - name: Lint
        run: npm run lint -ws

      - name: Build
        run: npm run build -ws

      - name: Publish Image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-sso-workflow-bridge-ui
          registry: ecr
          dockerfile: Dockerfile

      - name: Trigger Build Standalone
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_USER_TASKS }}
        run: gh workflow run main.yml -R littlehorse-enterprises/sso-workflow-bridge-api
