name: Main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: package-lock.json
          node-version: 20

      - name: Installing Dependencies
        working-directory: ui
        run: npm install

      - name: Linting
        working-directory: ui
        run: npm run lint

      - name: Build App
        working-directory: ui
        run: npm run build

      - name: Build and Publish
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-ui
          registry: ecr
          context: ui
          dockerfile: ui/Dockerfile

      - name: Trigger API Build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/littlehorse-enterprises/lh-user-tasks-api/dispatches \
            -d '{"event_type":"build","client_payload":{"repository":"${{ github.repository }}","sha":"${{ github.sha }}"}}'
