name: Main
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Image
        uses: littlehorse-enterprises/publish-image@v1
        with:
          image-name: lh-user-tasks-ui
          registry: ecr
          dockerfile: Dockerfile

      - name: Trigger API Build
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/littlehorse-enterprises/lh-user-tasks-api/dispatches \
            -d '{"event_type":"build","client_payload":{"repository":"${{ github.repository }}","sha":"${{ github.sha }}"}}'
