name: Lint and Build
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ui/package-lock.json
          node-version: 20

      - name: Installing Dependencies
        working-directory: ui
        run: npm install

      - name: Linting
        working-directory: ui
        run: npm run lint

      - name: Build App
        working-directory: ui
        run: npm run build
